//! Fleet seeds: GameUnit placements from the TNI AL sheet (task #28).
//!
//! `assets/fleet.json` holds one seed per active hull (125, Sept 2026):
//! name + hull number, class id (resolves against the [`Catalog`]),
//! role/origin prose, command (Satuan), and the administrative home base
//! (dermaga coords — NOT a live position). Generated by
//! `scripts/fleet_import.py`; this module only parses + sanity-checks.

use serde::Deserialize;

/// One hull seed: what a [`Catalog`] class IS DOING in a session once
/// placed — the GameUnit half of the Unit/GameUnit split (ADR-0005).
#[derive(Debug, Clone, Deserialize)]
pub struct FleetUnit {
    pub id: String,
    pub name: String,
    pub hull: String,
    pub class_id: String,
    pub role: String,
    pub origin: String,
    pub year: String,
    pub satuan: String,
    pub pangkalan: String,
    pub lokasi: String,
    pub lat: f64,
    pub lon: f64,
}

/// The loaded fleet: hull seeds in sheet order.
#[derive(Debug, Clone, Default)]
pub struct Fleet {
    units: Vec<FleetUnit>,
}

impl Fleet {
    /// Parse + sanity-check a fleet document. Fails loud: empty fleet,
    /// blank ids/names/class links, duplicate ids, or coords outside
    /// Indonesian waters.
    pub fn parse(text: &str) -> Result<Self, String> {
        #[derive(Deserialize)]
        struct Doc {
            units: Vec<FleetUnit>,
        }
        let doc: Doc = serde_json::from_str(text).map_err(|e| e.to_string())?;
        if doc.units.is_empty() {
            return Err("fleet has no units".into());
        }
        let mut seen = std::collections::HashSet::new();
        for u in &doc.units {
            if u.id.is_empty() || u.name.is_empty() || u.class_id.is_empty() {
                return Err(format!("fleet unit with blank id/name/class: {u:?}"));
            }
            if !seen.insert(u.id.clone()) {
                return Err(format!("duplicate fleet id `{}`", u.id));
            }
            // Namespace guard (REST mapping ticket): Minos wire ships key
            // as decimal unit ids ("13"), so seed ids must never be
            // all-digit — or a wire fix would collide with a sim hull and
            // the MergeSource owned-filter could not tell them apart.
            if u.id.bytes().all(|b| b.is_ascii_digit()) {
                return Err(format!(
                    "fleet id `{}` is all-digit: reserved for Minos wire ships",
                    u.id
                ));
            }
            if !( -11.0..=6.5).contains(&u.lat) || !(95.0..=141.5).contains(&u.lon) {
                return Err(format!("fleet unit {}: coords out of range ({}, {})", u.id, u.lat, u.lon));
            }
        }
        Ok(Self { units: doc.units })
    }

    /// Load the committed fleet asset.
    pub fn from_default_asset() -> Result<Self, String> {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/fleet.json");
        let text =
            std::fs::read_to_string(&path).map_err(|e| format!("fleet asset missing ({path:?}): {e}"))?;
        Self::parse(&text)
    }

    pub fn len(&self) -> usize {
        self.units.len()
    }

    pub fn is_empty(&self) -> bool {
        self.units.is_empty()
    }

    pub fn units(&self) -> &[FleetUnit] {
        &self.units
    }

    pub fn get(&self, id: &str) -> Option<&FleetUnit> {
        self.units.iter().find(|u| u.id == id)
    }

    /// Seeds of one class, in sheet order (placement source).
    pub fn by_class(&self, class_id: &str) -> Vec<&FleetUnit> {
        self.units.iter().filter(|u| u.class_id == class_id).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::catalog::Catalog;

    #[test]
    fn default_asset_loads_125_seeds() {
        let fleet = Fleet::from_default_asset().expect("asset parses");
        assert_eq!(fleet.len(), 125, "one seed per active hull");
        let nagapasa = fleet.get("kri-nagapasa-403").expect("Nagapasa 403 seeded");
        assert_eq!(nagapasa.class_id, "nagapasa-dsme-209-1400");
        assert_eq!(nagapasa.satuan, "Satsel Koarmada II");
        assert!((nagapasa.lat - -7.1917).abs() < 1e-4);
        assert!((nagapasa.lon - 112.735).abs() < 1e-4);
    }

    #[test]
    fn all_digit_ids_are_rejected_for_wire_namespace() {
        let doc = r#"{"units":[{"id":"13","name":"X","hull":"H","class_id":"c","role":"","origin":"","year":"","satuan":"","pangkalan":"","lokasi":"","lat":0.0,"lon":100.0}]}"#;
        let err = Fleet::parse(doc).unwrap_err();
        assert!(err.contains("all-digit"), "{err}");
    }

    #[test]
    fn every_seed_resolves_to_a_catalog_class() {
        let fleet = Fleet::from_default_asset().expect("fleet parses");
        let catalog = Catalog::from_default_asset().expect("catalog parses");
        for u in fleet.units() {
            assert!(catalog.class(&u.class_id).is_some(), "seed {} -> unknown class {}", u.id, u.class_id);
        }
    }

    #[test]
    fn sheet_duplicate_hull_gets_distinct_ids() {
        // The sheet lists KRI Lumba-Lumba 858 twice: both rows seed,
        // the second with a disambiguated id.
        let fleet = Fleet::from_default_asset().expect("fleet parses");
        assert!(fleet.get("kri-lumba-lumba-858").is_some());
        assert!(fleet.get("kri-lumba-lumba-858-2").is_some());
    }

    #[test]
    fn empty_fleet_fails_loud() {
        let err = Fleet::parse(r#"{"units": []}"#).unwrap_err();
        assert!(err.contains("no units"), "{err}");
    }

    #[test]
    fn out_of_range_coords_fail_loud() {
        let doc = r#"{"units": [{"id": "x", "name": "X", "hull": "1",
            "class_id": "c", "role": "", "origin": "", "year": "",
            "satuan": "", "pangkalan": "", "lokasi": "",
            "lat": 51.5, "lon": 0.0}]}"#;
        let err = Fleet::parse(doc).unwrap_err();
        assert!(err.contains("out of range"), "{err}");
    }
}
